version: '3'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 8081:80
    volumes:
      - ../regretslist:/var/www/apps/regretslist
    depends_on:
      - php
    container_name: Nginx_server
  php:
    build:
      context: ./php-fpm
    volumes:
      - ../regretslist:/var/www/apps/regretslist
    container_name: App_server
    depends_on:
      - db
  db:
    build:
      context: ./mysql
    env_file:
      - ./mysql/env/setting.env
    container_name: Mysql_server
    ports:
      - 13306:3306
    volumes:
      - db_data:/var/lib/mysql

  workspace:
    image: laradock/workspace:2.5-7.3
    volumes:
      - ../regretslist:/var/www/html
    working_dir: /var/www/html

volumes:
  db_data:
